// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package sender

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Sent is an event from the service notifying about a wallet sending transaction result
type Sent struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey            string   `protobuf:"bytes,5,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	Amount               string   `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Transaction          string   `protobuf:"bytes,8,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sent) Reset()         { *m = Sent{} }
func (m *Sent) String() string { return proto.CompactTextString(m) }
func (*Sent) ProtoMessage()    {}
func (*Sent) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_6df89beb7dbf4a14, []int{0}
}
func (m *Sent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sent.Unmarshal(m, b)
}
func (m *Sent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sent.Marshal(b, m, deterministic)
}
func (dst *Sent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sent.Merge(dst, src)
}
func (m *Sent) XXX_Size() int {
	return xxx_messageInfo_Sent.Size(m)
}
func (m *Sent) XXX_DiscardUnknown() {
	xxx_messageInfo_Sent.DiscardUnknown(m)
}

var xxx_messageInfo_Sent proto.InternalMessageInfo

func (m *Sent) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Sent) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Sent) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Sent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Sent) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Sent) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Sent) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Sent) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

// SentAck is a reply for Sent
type SentAck struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SentAck) Reset()         { *m = SentAck{} }
func (m *SentAck) String() string { return proto.CompactTextString(m) }
func (*SentAck) ProtoMessage()    {}
func (*SentAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_6df89beb7dbf4a14, []int{1}
}
func (m *SentAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SentAck.Unmarshal(m, b)
}
func (m *SentAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SentAck.Marshal(b, m, deterministic)
}
func (dst *SentAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SentAck.Merge(dst, src)
}
func (m *SentAck) XXX_Size() int {
	return xxx_messageInfo_SentAck.Size(m)
}
func (m *SentAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SentAck.DiscardUnknown(m)
}

var xxx_messageInfo_SentAck proto.InternalMessageInfo

func (m *SentAck) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SentAck) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Sent)(nil), "event.Sent")
	proto.RegisterType((*SentAck)(nil), "event.SentAck")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_event_6df89beb7dbf4a14) }

var fileDescriptor_event_6df89beb7dbf4a14 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x65, 0xd3, 0x38, 0xed, 0x55, 0x62, 0xb0, 0x10, 0xdc, 0xc0, 0x10, 0x65, 0xea, 0xd4,
	0x85, 0x89, 0x11, 0x24, 0x26, 0xc4, 0xd2, 0x6e, 0x6c, 0xa9, 0x73, 0x83, 0x55, 0x38, 0x57, 0xf6,
	0xa5, 0x12, 0xaf, 0xc4, 0xc3, 0xf0, 0x4c, 0x28, 0xd7, 0x46, 0xb0, 0x76, 0xb2, 0xbe, 0xcf, 0xa7,
	0x5f, 0xfa, 0x7f, 0x58, 0xd2, 0x91, 0x58, 0xd6, 0x87, 0x9c, 0x24, 0xf9, 0x4a, 0xa1, 0xfd, 0x31,
	0x30, 0xdb, 0x12, 0x8b, 0x47, 0xa8, 0xcb, 0x10, 0x02, 0x95, 0x82, 0xa6, 0x31, 0xab, 0xf9, 0x66,
	0x42, 0x7f, 0x03, 0x15, 0xe5, 0x9c, 0x32, 0xda, 0xc6, 0xac, 0x16, 0x9b, 0x13, 0xe8, 0x3d, 0xe5,
	0x63, 0x0c, 0x84, 0x57, 0xea, 0x27, 0xf4, 0xd7, 0x60, 0x63, 0x8f, 0x33, 0x95, 0x36, 0xf6, 0xfe,
	0x1e, 0x16, 0x87, 0x61, 0xf7, 0x11, 0xc3, 0x2b, 0x7d, 0x61, 0xa5, 0xfa, 0x4f, 0x8c, 0xe9, 0x92,
	0xf6, 0xc4, 0xe8, 0x4e, 0xe9, 0x0a, 0xfe, 0x16, 0x5c, 0xf7, 0x99, 0x06, 0x16, 0xac, 0x55, 0x9f,
	0xc9, 0x37, 0xb0, 0x94, 0xdc, 0x71, 0xe9, 0x82, 0xc4, 0xc4, 0x38, 0xd7, 0xcf, 0xff, 0xaa, 0x7d,
	0x84, 0x7a, 0xec, 0xf3, 0x14, 0xf6, 0x97, 0x56, 0x7a, 0x6e, 0xdf, 0x5d, 0x21, 0xee, 0x29, 0x7f,
	0xdb, 0xbb, 0xb7, 0xc8, 0xb2, 0x55, 0x58, 0x9f, 0x9f, 0x97, 0x71, 0xaf, 0x9d, 0xd3, 0xf5, 0x1e,
	0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xda, 0xbc, 0x83, 0x4c, 0x01, 0x00, 0x00,
}
