// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package sender

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Sent is an event from the service notifying about a wallet sending transaction result
type Sent struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey            string   `protobuf:"bytes,5,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	Amount               string   `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Transaction          string   `protobuf:"bytes,8,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sent) Reset()         { *m = Sent{} }
func (m *Sent) String() string { return proto.CompactTextString(m) }
func (*Sent) ProtoMessage()    {}
func (*Sent) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_77c465919cc27f3c, []int{0}
}
func (m *Sent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sent.Unmarshal(m, b)
}
func (m *Sent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sent.Marshal(b, m, deterministic)
}
func (dst *Sent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sent.Merge(dst, src)
}
func (m *Sent) XXX_Size() int {
	return xxx_messageInfo_Sent.Size(m)
}
func (m *Sent) XXX_DiscardUnknown() {
	xxx_messageInfo_Sent.DiscardUnknown(m)
}

var xxx_messageInfo_Sent proto.InternalMessageInfo

func (m *Sent) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Sent) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Sent) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Sent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Sent) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Sent) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Sent) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Sent) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

// SentAck is a reply for Sent
type SentAck struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SentAck) Reset()         { *m = SentAck{} }
func (m *SentAck) String() string { return proto.CompactTextString(m) }
func (*SentAck) ProtoMessage()    {}
func (*SentAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_77c465919cc27f3c, []int{1}
}
func (m *SentAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SentAck.Unmarshal(m, b)
}
func (m *SentAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SentAck.Marshal(b, m, deterministic)
}
func (dst *SentAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SentAck.Merge(dst, src)
}
func (m *SentAck) XXX_Size() int {
	return xxx_messageInfo_SentAck.Size(m)
}
func (m *SentAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SentAck.DiscardUnknown(m)
}

var xxx_messageInfo_SentAck proto.InternalMessageInfo

func (m *SentAck) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SentAck) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// Approved is an event from the service notifying about a wallet approvement result
type Approved struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey            string   `protobuf:"bytes,5,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Transaction          string   `protobuf:"bytes,6,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Approved) Reset()         { *m = Approved{} }
func (m *Approved) String() string { return proto.CompactTextString(m) }
func (*Approved) ProtoMessage()    {}
func (*Approved) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_77c465919cc27f3c, []int{2}
}
func (m *Approved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Approved.Unmarshal(m, b)
}
func (m *Approved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Approved.Marshal(b, m, deterministic)
}
func (dst *Approved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Approved.Merge(dst, src)
}
func (m *Approved) XXX_Size() int {
	return xxx_messageInfo_Approved.Size(m)
}
func (m *Approved) XXX_DiscardUnknown() {
	xxx_messageInfo_Approved.DiscardUnknown(m)
}

var xxx_messageInfo_Approved proto.InternalMessageInfo

func (m *Approved) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Approved) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Approved) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Approved) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Approved) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Approved) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

// ApprovedAck is a reply for Approved
type ApprovedAck struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApprovedAck) Reset()         { *m = ApprovedAck{} }
func (m *ApprovedAck) String() string { return proto.CompactTextString(m) }
func (*ApprovedAck) ProtoMessage()    {}
func (*ApprovedAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_77c465919cc27f3c, []int{3}
}
func (m *ApprovedAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApprovedAck.Unmarshal(m, b)
}
func (m *ApprovedAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApprovedAck.Marshal(b, m, deterministic)
}
func (dst *ApprovedAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApprovedAck.Merge(dst, src)
}
func (m *ApprovedAck) XXX_Size() int {
	return xxx_messageInfo_ApprovedAck.Size(m)
}
func (m *ApprovedAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ApprovedAck.DiscardUnknown(m)
}

var xxx_messageInfo_ApprovedAck proto.InternalMessageInfo

func (m *ApprovedAck) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ApprovedAck) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Sent)(nil), "event.Sent")
	proto.RegisterType((*SentAck)(nil), "event.SentAck")
	proto.RegisterType((*Approved)(nil), "event.Approved")
	proto.RegisterType((*ApprovedAck)(nil), "event.ApprovedAck")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_event_77c465919cc27f3c) }

var fileDescriptor_event_77c465919cc27f3c = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x92, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x40, 0xe5, 0xd0, 0x38, 0xe9, 0x45, 0x62, 0xb0, 0x10, 0xdc, 0xc0, 0x10, 0x65, 0xea, 0xd4,
	0x85, 0x89, 0x81, 0xa1, 0x48, 0x4c, 0x88, 0xa5, 0xdd, 0xd8, 0x52, 0xe7, 0x06, 0xab, 0x60, 0x5b,
	0xb6, 0x13, 0x89, 0xff, 0x61, 0xe2, 0x63, 0xf8, 0x26, 0x94, 0x6b, 0x22, 0x10, 0x4c, 0xb0, 0x30,
	0x45, 0xef, 0xc5, 0x3a, 0xf9, 0x59, 0x07, 0x15, 0x0d, 0x64, 0xd3, 0xda, 0x07, 0x97, 0x9c, 0xca,
	0x19, 0x9a, 0x77, 0x01, 0x8b, 0x1d, 0xd9, 0xa4, 0x10, 0x8a, 0xd8, 0x6b, 0x4d, 0x31, 0xa2, 0xa8,
	0xc5, 0xaa, 0xdc, 0xce, 0xa8, 0xce, 0x20, 0xa7, 0x10, 0x5c, 0xc0, 0xac, 0x16, 0xab, 0xe5, 0xf6,
	0x08, 0x7c, 0x9e, 0xc2, 0x60, 0x34, 0xe1, 0x09, 0xfb, 0x19, 0xd5, 0x29, 0x64, 0xa6, 0xc3, 0x05,
	0xcb, 0xcc, 0x74, 0xea, 0x12, 0x96, 0xbe, 0xdf, 0x3f, 0x19, 0x7d, 0x4f, 0x2f, 0x98, 0xb3, 0xfe,
	0x14, 0xe3, 0xf4, 0xe4, 0x0e, 0x64, 0x51, 0x1e, 0xa7, 0x33, 0xa8, 0x73, 0x90, 0xed, 0xb3, 0xeb,
	0x6d, 0xc2, 0x82, 0xf5, 0x44, 0xaa, 0x86, 0x2a, 0x85, 0xd6, 0xc6, 0x56, 0x27, 0xe3, 0x2c, 0x96,
	0xfc, 0xf3, 0xab, 0x6a, 0xae, 0xa1, 0x18, 0x7b, 0x36, 0xfa, 0xf0, 0xdb, 0xa4, 0xe6, 0x55, 0x40,
	0xb9, 0xf1, 0x3e, 0xb8, 0x81, 0xba, 0x7f, 0x7b, 0x8f, 0x6f, 0x85, 0xf2, 0x67, 0xe1, 0x0d, 0x54,
	0xf3, 0x2d, 0xff, 0x50, 0x79, 0xdb, 0x3c, 0xca, 0x48, 0xb6, 0xa3, 0xf0, 0x96, 0x5d, 0x3c, 0x18,
	0x9b, 0x76, 0x0c, 0xeb, 0xe9, 0x73, 0x37, 0x6e, 0xc5, 0x5e, 0xf2, 0x8e, 0x5c, 0x7d, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xeb, 0x9d, 0xd3, 0x13, 0x32, 0x02, 0x00, 0x00,
}
