// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package sender

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Send is a request to the service to send token to the specified wallet
type Send struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey            string   `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Amount               string   `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	IgnoreApprovement    bool     `protobuf:"varint,6,opt,name=ignoreApprovement,proto3" json:"ignoreApprovement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Send) Reset()         { *m = Send{} }
func (m *Send) String() string { return proto.CompactTextString(m) }
func (*Send) ProtoMessage()    {}
func (*Send) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *Send) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Send.Unmarshal(m, b)
}
func (m *Send) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Send.Marshal(b, m, deterministic)
}
func (m *Send) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Send.Merge(m, src)
}
func (m *Send) XXX_Size() int {
	return xxx_messageInfo_Send.Size(m)
}
func (m *Send) XXX_DiscardUnknown() {
	xxx_messageInfo_Send.DiscardUnknown(m)
}

var xxx_messageInfo_Send proto.InternalMessageInfo

func (m *Send) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Send) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Send) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Send) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Send) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Send) GetIgnoreApprovement() bool {
	if m != nil {
		return m.IgnoreApprovement
	}
	return false
}

// SendReply is a reply for Send
type SendReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendReply) Reset()         { *m = SendReply{} }
func (m *SendReply) String() string { return proto.CompactTextString(m) }
func (*SendReply) ProtoMessage()    {}
func (*SendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{1}
}

func (m *SendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReply.Unmarshal(m, b)
}
func (m *SendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReply.Marshal(b, m, deterministic)
}
func (m *SendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReply.Merge(m, src)
}
func (m *SendReply) XXX_Size() int {
	return xxx_messageInfo_SendReply.Size(m)
}
func (m *SendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendReply proto.InternalMessageInfo

func (m *SendReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// Approve is a request to the service to approve specified wallet
type Approve struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey            string   `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Approve) Reset()         { *m = Approve{} }
func (m *Approve) String() string { return proto.CompactTextString(m) }
func (*Approve) ProtoMessage()    {}
func (*Approve) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{2}
}

func (m *Approve) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Approve.Unmarshal(m, b)
}
func (m *Approve) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Approve.Marshal(b, m, deterministic)
}
func (m *Approve) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Approve.Merge(m, src)
}
func (m *Approve) XXX_Size() int {
	return xxx_messageInfo_Approve.Size(m)
}
func (m *Approve) XXX_DiscardUnknown() {
	xxx_messageInfo_Approve.DiscardUnknown(m)
}

var xxx_messageInfo_Approve proto.InternalMessageInfo

func (m *Approve) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Approve) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Approve) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

// ApproveReply is a reply for Approve
type ApproveReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApproveReply) Reset()         { *m = ApproveReply{} }
func (m *ApproveReply) String() string { return proto.CompactTextString(m) }
func (*ApproveReply) ProtoMessage()    {}
func (*ApproveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{3}
}

func (m *ApproveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveReply.Unmarshal(m, b)
}
func (m *ApproveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveReply.Marshal(b, m, deterministic)
}
func (m *ApproveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveReply.Merge(m, src)
}
func (m *ApproveReply) XXX_Size() int {
	return xxx_messageInfo_ApproveReply.Size(m)
}
func (m *ApproveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveReply.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveReply proto.InternalMessageInfo

func (m *ApproveReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ApproveReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Send)(nil), "request.Send")
	proto.RegisterType((*SendReply)(nil), "request.SendReply")
	proto.RegisterType((*Approve)(nil), "request.Approve")
	proto.RegisterType((*ApproveReply)(nil), "request.ApproveReply")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe) }

var fileDescriptor_7f73548e33e655fe = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x31, 0x4b, 0x03, 0x31,
	0x14, 0x80, 0xb9, 0xb3, 0xbd, 0xeb, 0x3d, 0x54, 0x30, 0x88, 0x44, 0x70, 0x28, 0x87, 0x43, 0x07,
	0xe9, 0xe2, 0x28, 0x08, 0xba, 0x8a, 0x83, 0xe9, 0xe6, 0x66, 0x93, 0x87, 0x04, 0xdb, 0x24, 0xbe,
	0x24, 0x85, 0xfe, 0xa5, 0xfe, 0x4a, 0xe9, 0xbb, 0x14, 0x07, 0x37, 0xe9, 0x14, 0xbe, 0xef, 0xc1,
	0xe3, 0x0b, 0x0f, 0xce, 0x08, 0xbf, 0x33, 0xc6, 0x34, 0x0f, 0xe4, 0x93, 0x17, 0x6d, 0xc1, 0x7e,
	0x57, 0xc1, 0x68, 0x81, 0xce, 0x08, 0x09, 0x6d, 0x44, 0xda, 0x58, 0x8d, 0xb2, 0x9a, 0x56, 0xb3,
	0x4e, 0x1d, 0x50, 0x9c, 0x43, 0x6d, 0x8d, 0xac, 0x59, 0xd6, 0xd6, 0x88, 0x1b, 0xe8, 0x42, 0x5e,
	0xae, 0xac, 0x7e, 0xc1, 0xad, 0x3c, 0x61, 0xfd, 0x2b, 0xc4, 0x25, 0x8c, 0x93, 0xff, 0x42, 0x27,
	0x47, 0x3c, 0x19, 0x40, 0x5c, 0x41, 0xf3, 0xb1, 0xf6, 0xd9, 0x25, 0x39, 0x66, 0x5d, 0x48, 0xdc,
	0xc1, 0x85, 0xfd, 0x74, 0x9e, 0xf0, 0x29, 0x04, 0xf2, 0x1b, 0x5c, 0xa3, 0x4b, 0xb2, 0x99, 0x56,
	0xb3, 0x89, 0xfa, 0x3b, 0xe8, 0x1f, 0xa0, 0xdb, 0xb7, 0x2a, 0x0c, 0xab, 0x2d, 0x07, 0x67, 0xad,
	0x31, 0x46, 0x0e, 0x9e, 0xa8, 0x03, 0xee, 0x13, 0x90, 0xc8, 0x53, 0x69, 0x1e, 0xa0, 0x7f, 0x83,
	0xb6, 0xec, 0x3a, 0xd6, 0x5f, 0xfb, 0x47, 0x38, 0x2d, 0x2b, 0xff, 0x95, 0xf4, 0x7c, 0xfb, 0xde,
	0x44, 0x74, 0x06, 0x69, 0x57, 0x5f, 0xbf, 0x5a, 0x97, 0x16, 0x0c, 0xf3, 0xf2, 0xa8, 0xe1, 0x44,
	0xcb, 0x86, 0x4f, 0x76, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x13, 0x49, 0x78, 0x2e, 0xc3, 0x01,
	0x00, 0x00,
}
