// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package sender

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Send is a request to the service to send token to the specified wallet
type Send struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey            string   `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Amount               string   `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Send) Reset()         { *m = Send{} }
func (m *Send) String() string { return proto.CompactTextString(m) }
func (*Send) ProtoMessage()    {}
func (*Send) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_73175baf00b9b33d, []int{0}
}
func (m *Send) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Send.Unmarshal(m, b)
}
func (m *Send) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Send.Marshal(b, m, deterministic)
}
func (dst *Send) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Send.Merge(dst, src)
}
func (m *Send) XXX_Size() int {
	return xxx_messageInfo_Send.Size(m)
}
func (m *Send) XXX_DiscardUnknown() {
	xxx_messageInfo_Send.DiscardUnknown(m)
}

var xxx_messageInfo_Send proto.InternalMessageInfo

func (m *Send) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Send) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Send) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Send) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Send) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// SendReply is a reply for Send
type SendReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendReply) Reset()         { *m = SendReply{} }
func (m *SendReply) String() string { return proto.CompactTextString(m) }
func (*SendReply) ProtoMessage()    {}
func (*SendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_73175baf00b9b33d, []int{1}
}
func (m *SendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReply.Unmarshal(m, b)
}
func (m *SendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReply.Marshal(b, m, deterministic)
}
func (dst *SendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReply.Merge(dst, src)
}
func (m *SendReply) XXX_Size() int {
	return xxx_messageInfo_SendReply.Size(m)
}
func (m *SendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendReply proto.InternalMessageInfo

func (m *SendReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Send)(nil), "request.Send")
	proto.RegisterType((*SendReply)(nil), "request.SendReply")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_request_73175baf00b9b33d) }

var fileDescriptor_request_73175baf00b9b33d = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x6a, 0xb8,
	0x58, 0x82, 0x53, 0xf3, 0x52, 0x84, 0x24, 0xb8, 0xd8, 0x8b, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09,
	0x26, 0xb0, 0x20, 0x53, 0x66, 0x8a, 0x90, 0x0c, 0x17, 0x67, 0x41, 0x69, 0x52, 0x4e, 0x66, 0xb2,
	0x77, 0x6a, 0xa5, 0x04, 0x33, 0x58, 0x18, 0x21, 0x20, 0x24, 0xc2, 0xc5, 0x5a, 0x92, 0x9f, 0x9d,
	0x9a, 0x27, 0xc1, 0x02, 0x96, 0x81, 0x70, 0x84, 0xc4, 0xb8, 0xd8, 0x12, 0x73, 0xf3, 0x4b, 0xf3,
	0x4a, 0x24, 0x58, 0xc1, 0xc2, 0x50, 0x9e, 0x92, 0x35, 0x17, 0x27, 0xc8, 0xf6, 0xa0, 0xd4, 0x82,
	0x9c, 0x4a, 0xb0, 0x13, 0x4a, 0x93, 0x93, 0x53, 0x8b, 0x8b, 0xc1, 0x4e, 0xe0, 0x08, 0x82, 0x71,
	0x41, 0x86, 0xa6, 0x16, 0x15, 0xe5, 0x17, 0x41, 0x5d, 0x01, 0xe1, 0x38, 0xa9, 0x44, 0xb1, 0x15,
	0xa7, 0xe6, 0xa5, 0xa4, 0x16, 0xad, 0x62, 0x92, 0xf4, 0xcd, 0xcc, 0x2b, 0x09, 0x06, 0x73, 0xf4,
	0xa0, 0x54, 0x10, 0xc4, 0x83, 0x49, 0x6c, 0x60, 0x0f, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xec, 0xb2, 0x4c, 0xf2, 0x01, 0x01, 0x00, 0x00,
}
