// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sender.proto

package sender

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// SendRequest is a request to the service to send token to the specified wallet
type SendRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pubkey               string   `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Amount               string   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sender_ee767223e3515f3f, []int{0}
}
func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (dst *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(dst, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SendRequest) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *SendRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SendRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// SendReply is a reply for SendRequest
type SendReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendReply) Reset()         { *m = SendReply{} }
func (m *SendReply) String() string { return proto.CompactTextString(m) }
func (*SendReply) ProtoMessage()    {}
func (*SendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_sender_ee767223e3515f3f, []int{1}
}
func (m *SendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReply.Unmarshal(m, b)
}
func (m *SendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReply.Marshal(b, m, deterministic)
}
func (dst *SendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReply.Merge(dst, src)
}
func (m *SendReply) XXX_Size() int {
	return xxx_messageInfo_SendReply.Size(m)
}
func (m *SendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendReply proto.InternalMessageInfo

func (m *SendReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// SentEvent is an event from the service notifying about a wallet sending transaction result
type SentEvent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Transaction          string   `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SentEvent) Reset()         { *m = SentEvent{} }
func (m *SentEvent) String() string { return proto.CompactTextString(m) }
func (*SentEvent) ProtoMessage()    {}
func (*SentEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_sender_ee767223e3515f3f, []int{2}
}
func (m *SentEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SentEvent.Unmarshal(m, b)
}
func (m *SentEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SentEvent.Marshal(b, m, deterministic)
}
func (dst *SentEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SentEvent.Merge(dst, src)
}
func (m *SentEvent) XXX_Size() int {
	return xxx_messageInfo_SentEvent.Size(m)
}
func (m *SentEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SentEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SentEvent proto.InternalMessageInfo

func (m *SentEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SentEvent) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SentEvent) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SentEvent) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

// SentEventReply is a reply for SentEvent
type SentEventReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SentEventReply) Reset()         { *m = SentEventReply{} }
func (m *SentEventReply) String() string { return proto.CompactTextString(m) }
func (*SentEventReply) ProtoMessage()    {}
func (*SentEventReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_sender_ee767223e3515f3f, []int{3}
}
func (m *SentEventReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SentEventReply.Unmarshal(m, b)
}
func (m *SentEventReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SentEventReply.Marshal(b, m, deterministic)
}
func (dst *SentEventReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SentEventReply.Merge(dst, src)
}
func (m *SentEventReply) XXX_Size() int {
	return xxx_messageInfo_SentEventReply.Size(m)
}
func (m *SentEventReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SentEventReply.DiscardUnknown(m)
}

var xxx_messageInfo_SentEventReply proto.InternalMessageInfo

func (m *SentEventReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SentEventReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*SendRequest)(nil), "sender.SendRequest")
	proto.RegisterType((*SendReply)(nil), "sender.SendReply")
	proto.RegisterType((*SentEvent)(nil), "sender.SentEvent")
	proto.RegisterType((*SentEventReply)(nil), "sender.SentEventReply")
}

func init() { proto.RegisterFile("sender.proto", fileDescriptor_sender_ee767223e3515f3f) }

var fileDescriptor_sender_ee767223e3515f3f = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xcd, 0x8e, 0x82, 0x30,
	0x14, 0x85, 0x43, 0x99, 0x61, 0x86, 0xcb, 0x84, 0x45, 0x33, 0x31, 0x5d, 0x92, 0xae, 0x5c, 0xb9,
	0x71, 0xe9, 0xc6, 0x8d, 0x2f, 0x80, 0x4f, 0x00, 0xed, 0x5d, 0x10, 0xa4, 0xc5, 0xfe, 0x98, 0xf0,
	0xf6, 0x86, 0x16, 0x0d, 0x89, 0x71, 0xe3, 0xf2, 0x3b, 0xb9, 0x3d, 0xdf, 0x49, 0xe1, 0xcf, 0xa2,
	0x92, 0x68, 0x76, 0xa3, 0xd1, 0x4e, 0xd3, 0x2c, 0x12, 0x17, 0x50, 0x9c, 0x51, 0xc9, 0x1a, 0xaf,
	0x1e, 0xad, 0xa3, 0x25, 0x90, 0x4e, 0xb2, 0xa4, 0x4a, 0xb6, 0x79, 0x4d, 0x3a, 0x49, 0x37, 0x90,
	0x8d, 0xbe, 0xed, 0x71, 0x62, 0x24, 0x64, 0x0b, 0xd1, 0x7f, 0xf8, 0x76, 0xba, 0x47, 0xc5, 0xd2,
	0x10, 0x47, 0x98, 0xaf, 0x9b, 0x41, 0x7b, 0xe5, 0xd8, 0x57, 0xbc, 0x8e, 0xc4, 0x0f, 0x90, 0x47,
	0xc9, 0x78, 0x99, 0x28, 0x83, 0x1f, 0xeb, 0x85, 0x40, 0x6b, 0x83, 0xe7, 0xb7, 0x7e, 0xe0, 0x5c,
	0x8a, 0xc6, 0x68, 0xb3, 0xb8, 0x22, 0xf0, 0x21, 0x3c, 0x76, 0xa7, 0x1b, 0xaa, 0xd7, 0x7d, 0xab,
	0x32, 0xf2, 0xa6, 0x2c, 0x5d, 0x95, 0xd1, 0x0a, 0x0a, 0x67, 0x1a, 0x65, 0x1b, 0xe1, 0x3a, 0xad,
	0x96, 0x99, 0xeb, 0x88, 0x1f, 0xa1, 0x7c, 0xea, 0x3e, 0x1a, 0xdc, 0x66, 0xe1, 0x87, 0xf7, 0xf7,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0xa6, 0x71, 0x86, 0x71, 0x01, 0x00, 0x00,
}
