// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package wallet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AddRemoveRequest is a request to the service to add or remove a wallet by it's public key
type AddRemoveRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	PublicKey            []string `protobuf:"bytes,2,rep,name=publicKey,proto3" json:"publicKey,omitempty"`
	Add                  bool     `protobuf:"varint,3,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoveRequest) Reset()         { *m = AddRemoveRequest{} }
func (m *AddRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*AddRemoveRequest) ProtoMessage()    {}
func (*AddRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_c018d72d5d43730a, []int{0}
}
func (m *AddRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoveRequest.Unmarshal(m, b)
}
func (m *AddRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoveRequest.Marshal(b, m, deterministic)
}
func (dst *AddRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoveRequest.Merge(dst, src)
}
func (m *AddRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_AddRemoveRequest.Size(m)
}
func (m *AddRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoveRequest proto.InternalMessageInfo

func (m *AddRemoveRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *AddRemoveRequest) GetPublicKey() []string {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *AddRemoveRequest) GetAdd() bool {
	if m != nil {
		return m.Add
	}
	return false
}

// AddRemoveReply is a reply for AddRemoveRequest
type AddRemoveReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoveReply) Reset()         { *m = AddRemoveReply{} }
func (m *AddRemoveReply) String() string { return proto.CompactTextString(m) }
func (*AddRemoveReply) ProtoMessage()    {}
func (*AddRemoveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_c018d72d5d43730a, []int{1}
}
func (m *AddRemoveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoveReply.Unmarshal(m, b)
}
func (m *AddRemoveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoveReply.Marshal(b, m, deterministic)
}
func (dst *AddRemoveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoveReply.Merge(dst, src)
}
func (m *AddRemoveReply) XXX_Size() int {
	return xxx_messageInfo_AddRemoveReply.Size(m)
}
func (m *AddRemoveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoveReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoveReply proto.InternalMessageInfo

func (m *AddRemoveReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddRemoveReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// RefillEvent is an event from the service notifying about a wallet refilling transaction
type RefillEvent struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Amount               string   `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Transaction          string   `protobuf:"bytes,6,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefillEvent) Reset()         { *m = RefillEvent{} }
func (m *RefillEvent) String() string { return proto.CompactTextString(m) }
func (*RefillEvent) ProtoMessage()    {}
func (*RefillEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_c018d72d5d43730a, []int{2}
}
func (m *RefillEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefillEvent.Unmarshal(m, b)
}
func (m *RefillEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefillEvent.Marshal(b, m, deterministic)
}
func (dst *RefillEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefillEvent.Merge(dst, src)
}
func (m *RefillEvent) XXX_Size() int {
	return xxx_messageInfo_RefillEvent.Size(m)
}
func (m *RefillEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RefillEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RefillEvent proto.InternalMessageInfo

func (m *RefillEvent) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *RefillEvent) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *RefillEvent) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *RefillEvent) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefillEvent) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *RefillEvent) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

// RefillEventReply is a reply for RefilledEvent
type RefillEventReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefillEventReply) Reset()         { *m = RefillEventReply{} }
func (m *RefillEventReply) String() string { return proto.CompactTextString(m) }
func (*RefillEventReply) ProtoMessage()    {}
func (*RefillEventReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_c018d72d5d43730a, []int{3}
}
func (m *RefillEventReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefillEventReply.Unmarshal(m, b)
}
func (m *RefillEventReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefillEventReply.Marshal(b, m, deterministic)
}
func (dst *RefillEventReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefillEventReply.Merge(dst, src)
}
func (m *RefillEventReply) XXX_Size() int {
	return xxx_messageInfo_RefillEventReply.Size(m)
}
func (m *RefillEventReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RefillEventReply.DiscardUnknown(m)
}

var xxx_messageInfo_RefillEventReply proto.InternalMessageInfo

func (m *RefillEventReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RefillEventReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*AddRemoveRequest)(nil), "wallet.AddRemoveRequest")
	proto.RegisterType((*AddRemoveReply)(nil), "wallet.AddRemoveReply")
	proto.RegisterType((*RefillEvent)(nil), "wallet.RefillEvent")
	proto.RegisterType((*RefillEventReply)(nil), "wallet.RefillEventReply")
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor_wallet_c018d72d5d43730a) }

var fileDescriptor_wallet_c018d72d5d43730a = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0xa6, 0x0d, 0xcd, 0x15, 0xa1, 0xc8, 0x42, 0xc8, 0x03, 0x43, 0x94, 0x29, 0x13,
	0x0b, 0x7f, 0x00, 0x90, 0x98, 0xd8, 0x3c, 0xb3, 0xb8, 0xce, 0x55, 0x8a, 0x70, 0x7c, 0xc1, 0x76,
	0x82, 0xfa, 0x93, 0xf8, 0x97, 0xa8, 0x17, 0x2a, 0xc2, 0x08, 0xdb, 0xfb, 0x9e, 0xa5, 0xf7, 0x9e,
	0x75, 0x70, 0xf9, 0x61, 0x9c, 0xc3, 0x74, 0x37, 0x04, 0x4a, 0x24, 0xf3, 0x99, 0xea, 0x57, 0x28,
	0x1f, 0xdb, 0x56, 0x63, 0x4f, 0x13, 0x6a, 0x7c, 0x1f, 0x31, 0x26, 0xa9, 0xe0, 0x22, 0x62, 0x98,
	0x3a, 0x8b, 0x4a, 0x54, 0xa2, 0x29, 0xf4, 0x19, 0xe5, 0x2d, 0x14, 0xc3, 0xb8, 0x77, 0x9d, 0x7d,
	0xc1, 0xa3, 0x5a, 0x55, 0x59, 0x53, 0xe8, 0x1f, 0x43, 0x96, 0x90, 0x99, 0xb6, 0x55, 0x59, 0x25,
	0x9a, 0xad, 0x3e, 0xc9, 0xfa, 0x01, 0xae, 0x16, 0xe9, 0x83, 0x3b, 0x72, 0xf6, 0x68, 0x2d, 0xc6,
	0xc8, 0xd9, 0x5b, 0x7d, 0x46, 0x79, 0x0d, 0x1b, 0x0c, 0x81, 0x82, 0x5a, 0x71, 0xe7, 0x0c, 0xf5,
	0xa7, 0x80, 0x9d, 0xc6, 0x43, 0xe7, 0xdc, 0xf3, 0x84, 0xfe, 0x0f, 0xdb, 0xc4, 0xef, 0x6d, 0x12,
	0xd6, 0x87, 0x40, 0x3d, 0x8f, 0x2b, 0x34, 0xeb, 0x53, 0x63, 0xa2, 0x37, 0xf4, 0x6a, 0x3d, 0x37,
	0x32, 0xc8, 0x1b, 0xc8, 0x4d, 0x4f, 0xa3, 0x4f, 0x6a, 0xc3, 0xf6, 0x37, 0xc9, 0x0a, 0x76, 0x29,
	0x18, 0x1f, 0x8d, 0x4d, 0x1d, 0x79, 0x95, 0xf3, 0xe3, 0xd2, 0xaa, 0x9f, 0xa0, 0x5c, 0x4c, 0xfd,
	0xd7, 0x7f, 0xf7, 0x39, 0x9f, 0xe7, 0xfe, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xda, 0xbf, 0xaa,
	0xae, 0x01, 0x00, 0x00,
}
