// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package wallet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AddRemoveRequest is a request to the service to add or remove a wallet by it's public key
type AddRemoveRequest struct {
	Pubkey               []string `protobuf:"bytes,1,rep,name=pubkey,proto3" json:"pubkey,omitempty"`
	Add                  bool     `protobuf:"varint,2,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoveRequest) Reset()         { *m = AddRemoveRequest{} }
func (m *AddRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*AddRemoveRequest) ProtoMessage()    {}
func (*AddRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_050a3a384059b35e, []int{0}
}
func (m *AddRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoveRequest.Unmarshal(m, b)
}
func (m *AddRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoveRequest.Marshal(b, m, deterministic)
}
func (dst *AddRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoveRequest.Merge(dst, src)
}
func (m *AddRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_AddRemoveRequest.Size(m)
}
func (m *AddRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoveRequest proto.InternalMessageInfo

func (m *AddRemoveRequest) GetPubkey() []string {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *AddRemoveRequest) GetAdd() bool {
	if m != nil {
		return m.Add
	}
	return false
}

// AddRemoveReply is a reply for AddRemoveRequest
type AddRemoveReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoveReply) Reset()         { *m = AddRemoveReply{} }
func (m *AddRemoveReply) String() string { return proto.CompactTextString(m) }
func (*AddRemoveReply) ProtoMessage()    {}
func (*AddRemoveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_050a3a384059b35e, []int{1}
}
func (m *AddRemoveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoveReply.Unmarshal(m, b)
}
func (m *AddRemoveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoveReply.Marshal(b, m, deterministic)
}
func (dst *AddRemoveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoveReply.Merge(dst, src)
}
func (m *AddRemoveReply) XXX_Size() int {
	return xxx_messageInfo_AddRemoveReply.Size(m)
}
func (m *AddRemoveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoveReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoveReply proto.InternalMessageInfo

func (m *AddRemoveReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddRemoveReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// RefilledEvent is an event from the service notifying about a wallet refilling transaction
type RefilledEvent struct {
	Pubkey               string   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Transaction          string   `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefilledEvent) Reset()         { *m = RefilledEvent{} }
func (m *RefilledEvent) String() string { return proto.CompactTextString(m) }
func (*RefilledEvent) ProtoMessage()    {}
func (*RefilledEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_050a3a384059b35e, []int{2}
}
func (m *RefilledEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefilledEvent.Unmarshal(m, b)
}
func (m *RefilledEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefilledEvent.Marshal(b, m, deterministic)
}
func (dst *RefilledEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefilledEvent.Merge(dst, src)
}
func (m *RefilledEvent) XXX_Size() int {
	return xxx_messageInfo_RefilledEvent.Size(m)
}
func (m *RefilledEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RefilledEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RefilledEvent proto.InternalMessageInfo

func (m *RefilledEvent) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *RefilledEvent) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefilledEvent) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *RefilledEvent) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

// RefilledEventReply is a reply for RefilledEvent
type RefilledEventReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefilledEventReply) Reset()         { *m = RefilledEventReply{} }
func (m *RefilledEventReply) String() string { return proto.CompactTextString(m) }
func (*RefilledEventReply) ProtoMessage()    {}
func (*RefilledEventReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_050a3a384059b35e, []int{3}
}
func (m *RefilledEventReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefilledEventReply.Unmarshal(m, b)
}
func (m *RefilledEventReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefilledEventReply.Marshal(b, m, deterministic)
}
func (dst *RefilledEventReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefilledEventReply.Merge(dst, src)
}
func (m *RefilledEventReply) XXX_Size() int {
	return xxx_messageInfo_RefilledEventReply.Size(m)
}
func (m *RefilledEventReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RefilledEventReply.DiscardUnknown(m)
}

var xxx_messageInfo_RefilledEventReply proto.InternalMessageInfo

func (m *RefilledEventReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RefilledEventReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*AddRemoveRequest)(nil), "wallet.AddRemoveRequest")
	proto.RegisterType((*AddRemoveReply)(nil), "wallet.AddRemoveReply")
	proto.RegisterType((*RefilledEvent)(nil), "wallet.RefilledEvent")
	proto.RegisterType((*RefilledEventReply)(nil), "wallet.RefilledEventReply")
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor_wallet_050a3a384059b35e) }

var fileDescriptor_wallet_050a3a384059b35e = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0x89, 0x75, 0xab, 0x3b, 0x7e, 0xb0, 0x84, 0x45, 0x72, 0x2c, 0x39, 0xed, 0xc9, 0x8b,
	0x57, 0x0f, 0x0a, 0xfa, 0x07, 0xf2, 0x0f, 0xd2, 0x66, 0x84, 0xd2, 0x34, 0xa9, 0xf9, 0x68, 0xe9,
	0xbf, 0x97, 0x26, 0x16, 0xda, 0xeb, 0xde, 0xf2, 0x64, 0xde, 0x97, 0x67, 0x18, 0x78, 0x9c, 0xa4,
	0xd6, 0x18, 0x5e, 0x07, 0x67, 0x83, 0xa5, 0x65, 0x26, 0xfe, 0x0e, 0xa7, 0x4f, 0xa5, 0x04, 0xf6,
	0x76, 0x44, 0x81, 0xbf, 0x11, 0x7d, 0xa0, 0x2f, 0x50, 0x0e, 0xb1, 0xee, 0x70, 0x66, 0xa4, 0x2a,
	0x2e, 0x47, 0xf1, 0x4f, 0xf4, 0x04, 0x85, 0x54, 0x8a, 0xdd, 0x54, 0xe4, 0x72, 0x2f, 0x96, 0x27,
	0xff, 0x80, 0xe7, 0x4d, 0x7b, 0xd0, 0x33, 0x65, 0x70, 0xe7, 0x63, 0xd3, 0xa0, 0xf7, 0x8c, 0xa4,
	0xdc, 0x8a, 0xf4, 0x0c, 0x07, 0x74, 0xce, 0xba, 0xd4, 0x3f, 0x8a, 0x0c, 0x7c, 0x82, 0x27, 0x81,
	0x3f, 0xad, 0xd6, 0xa8, 0xbe, 0x47, 0x34, 0x7b, 0x39, 0xd9, 0xc8, 0xcf, 0x70, 0x08, 0xb6, 0x43,
	0xb3, 0xd6, 0x13, 0x2c, 0x69, 0xd9, 0xdb, 0x68, 0x02, 0x2b, 0x72, 0x3a, 0x13, 0xad, 0xe0, 0x21,
	0x38, 0x69, 0xbc, 0x6c, 0x42, 0x6b, 0x0d, 0xbb, 0x4d, 0xc3, 0xed, 0x17, 0xff, 0x02, 0xba, 0x13,
	0x5f, 0xb5, 0x7e, 0x5d, 0xa6, 0x6b, 0xbe, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x78, 0xdf, 0x13,
	0xc4, 0x5d, 0x01, 0x00, 0x00,
}
