{
 "title": "Mint Sender",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   { "name": "interval", "label": "Interval", "query": "5s, 30s, 1m, 5m, 10m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(gmmintsender_sender_tx_volume{job=\"$job\"}[$interval])",
     "legendFormat": "Sent [{{token}}]"
    },
    {
     "expr": "max_over_time(gmmintsender_watcher_tx_volume{job=\"$job\"}[$interval])",
     "legendFormat": "Received [{{token}}]"
    }
   ]
  },
  {
   "title": "Service Methods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gmmintsender_sender_sendersvc_request_duration_sum{job=\"$job\"}[$interval]) / gmmintsender_sender_sendersvc_request_duration_count{job=\"$job\"}",
     "legendFormat": "Sender [{{method}}]"
    },
    {
     "expr": "avg_over_time(gmmintsender_watcher_walletsvc_request_duration_sum{job=\"$job\"}[$interval]) / gmmintsender_watcher_walletsvc_request_duration_count{job=\"$job\"}",
     "legendFormat": "Watcher [{{method}}]"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gmmintsender_sender_task_duration_sum{job=\"$job\"}[$interval]) / gmmintsender_sender_task_duration_count{job=\"$job\"}",
     "legendFormat": "Sender [{{task}}]"
    },
    {
     "expr": "avg_over_time(gmmintsender_watcher_task_duration_sum{job=\"$job\"}[$interval]) / gmmintsender_watcher_task_duration_count{job=\"$job\"}",
     "legendFormat": "Watcher [{{task}}]"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max_over_time(gmmintsender_sender_errors{job=\"$job\"}[$interval])",
     "legendFormat": "Sender [{{source}}]"
    },
    {
     "expr": "max_over_time(gmmintsender_watcher_errors{job=\"$job\"}[$interval])",
     "legendFormat": "Watcher [{{source}}]"
    }
   ]
  },
  {
   "title": "Wallets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gmmintsender_sender_wallets{job=\"$job\"}",
     "legendFormat": "{{sender}} [{{token}}]"
    },
    {
     "expr": "gmmintsender_watcher_wallets{job=\"$job\"}",
     "legendFormat": "ROI Wallets"
    }
   ]
  },
  {
   "title": "Nats API Methods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gmmintsender_sender_natsapi_request_duration_sum{job=\"$job\"}[$interval]) / gmmintsender_sender_natsapi_request_duration_count{job=\"$job\"}",
     "legendFormat": "Sender [{{method}}]"
    },
    {
     "expr": "avg_over_time(gmmintsender_watcher_natsapi_request_duration_sum{job=\"$job\"}[$interval]) / gmmintsender_watcher_natsapi_request_duration_count{job=\"$job\"}",
     "legendFormat": "Watcher [{{method}}]"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gmmintsender_sender_queue_size{job=\"$job\"}[$interval])",
     "legendFormat": "Sender [{{queue}}]"
    },
    {
     "expr": "avg_over_time(gmmintsender_watcher_queue_size{job=\"$job\"}[$interval])",
     "legendFormat": "Watcher [{{queue}}]"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time( process_virtual_memory_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "Virtual"
    },
    {
     "expr": "max_over_time( process_resident_memory_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "Resident"
    },
    {
     "expr": "max_over_time( go_memstats_sys_bytes{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "App"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max_over_time(go_goroutines{job=\"$job\"}[3m])",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "max_over_time(go_threads{job=\"$job\"}[3m])",
     "legendFormat": "Threads"
    }
   ]
  }
 ]
}