// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package watcher

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Refill is an event from the service notifying about a wallet refilling transaction
type Refill struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Amount               string   `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Transaction          string   `protobuf:"bytes,6,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Refill) Reset()         { *m = Refill{} }
func (m *Refill) String() string { return proto.CompactTextString(m) }
func (*Refill) ProtoMessage()    {}
func (*Refill) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_4b31ab7e1f65d4e0, []int{0}
}
func (m *Refill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Refill.Unmarshal(m, b)
}
func (m *Refill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Refill.Marshal(b, m, deterministic)
}
func (dst *Refill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Refill.Merge(dst, src)
}
func (m *Refill) XXX_Size() int {
	return xxx_messageInfo_Refill.Size(m)
}
func (m *Refill) XXX_DiscardUnknown() {
	xxx_messageInfo_Refill.DiscardUnknown(m)
}

var xxx_messageInfo_Refill proto.InternalMessageInfo

func (m *Refill) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Refill) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Refill) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Refill) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Refill) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Refill) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

// RefillAck is a reply for Refill
type RefillAck struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefillAck) Reset()         { *m = RefillAck{} }
func (m *RefillAck) String() string { return proto.CompactTextString(m) }
func (*RefillAck) ProtoMessage()    {}
func (*RefillAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_4b31ab7e1f65d4e0, []int{1}
}
func (m *RefillAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefillAck.Unmarshal(m, b)
}
func (m *RefillAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefillAck.Marshal(b, m, deterministic)
}
func (dst *RefillAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefillAck.Merge(dst, src)
}
func (m *RefillAck) XXX_Size() int {
	return xxx_messageInfo_RefillAck.Size(m)
}
func (m *RefillAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RefillAck.DiscardUnknown(m)
}

var xxx_messageInfo_RefillAck proto.InternalMessageInfo

func (m *RefillAck) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RefillAck) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Refill)(nil), "event.Refill")
	proto.RegisterType((*RefillAck)(nil), "event.RefillAck")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_event_4b31ab7e1f65d4e0) }

var fileDescriptor_event_4b31ab7e1f65d4e0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4b, 0x03, 0x41,
	0x10, 0x46, 0xb9, 0x98, 0xbb, 0x78, 0x93, 0x6e, 0x10, 0x99, 0xc2, 0x22, 0x04, 0x0b, 0xab, 0x6b,
	0x2c, 0xad, 0x14, 0xac, 0xc4, 0xe6, 0x2c, 0x04, 0xbb, 0xcd, 0x3a, 0xc1, 0x25, 0x97, 0xdd, 0x30,
	0x3b, 0x17, 0xf1, 0xff, 0x58, 0xf9, 0x2b, 0x25, 0xb3, 0x09, 0xda, 0xed, 0x7b, 0x5f, 0xb1, 0x8f,
	0x81, 0x39, 0xef, 0x39, 0x6a, 0xb7, 0x93, 0xa4, 0x09, 0x6b, 0x83, 0xe5, 0x77, 0x05, 0x4d, 0xcf,
	0xeb, 0x30, 0x0c, 0x48, 0x30, 0xcb, 0x2c, 0xfb, 0xe0, 0x99, 0xaa, 0x45, 0x75, 0xd3, 0xf6, 0x27,
	0xc4, 0x2b, 0x68, 0x77, 0xe3, 0x6a, 0x08, 0xfe, 0x89, 0xbf, 0x68, 0x62, 0xdb, 0x9f, 0x40, 0x84,
	0xe9, 0x5a, 0xd2, 0x96, 0xce, 0x6c, 0xb0, 0x37, 0x5e, 0x40, 0xad, 0x69, 0xc3, 0x91, 0xa6, 0x26,
	0x0b, 0xe0, 0x25, 0x34, 0x6e, 0x9b, 0xc6, 0xa8, 0x54, 0x9b, 0x3e, 0x12, 0x2e, 0x60, 0xae, 0xe2,
	0x62, 0x76, 0x5e, 0x43, 0x8a, 0xd4, 0xd8, 0xf8, 0x5f, 0x2d, 0xef, 0xa0, 0x2d, 0x95, 0xf7, 0x7e,
	0x63, 0xa1, 0xa3, 0xf7, 0x9c, 0xb3, 0x85, 0x9e, 0xf7, 0x27, 0x3c, 0x7c, 0xcb, 0x22, 0x49, 0x8e,
	0x91, 0x05, 0x1e, 0xae, 0xdf, 0x66, 0x9f, 0x4e, 0xfd, 0x07, 0xcb, 0xcf, 0x84, 0x9e, 0x43, 0xd4,
	0x17, 0x8e, 0xef, 0x2c, 0xdd, 0x6b, 0x91, 0xdd, 0xe3, 0xe1, 0x12, 0xab, 0xc6, 0xee, 0x72, 0xfb,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x63, 0x9d, 0x0e, 0x26, 0x01, 0x00, 0x00,
}
