// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.10.1
// source: mintwatcher_event.proto

package watcher

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Refill is an event from the service notifying about a wallet refilling transaction
type Refill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service     string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`         // Service name (to differentiate multiple requestors): 1..64
	PublicKey   string `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`     // Destination (watching) wallet address in Base58
	From        string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`               // Source wallet address in Base58
	Token       string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`             // GOLD or MNT
	Amount      string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`           // Token amount in major units: 1.234 (18 decimal places)
	Transaction string `protobuf:"bytes,6,opt,name=transaction,proto3" json:"transaction,omitempty"` // Digest of the refilling tx in Base58
}

func (x *Refill) Reset() {
	*x = Refill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mintwatcher_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Refill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refill) ProtoMessage() {}

func (x *Refill) ProtoReflect() protoreflect.Message {
	mi := &file_mintwatcher_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refill.ProtoReflect.Descriptor instead.
func (*Refill) Descriptor() ([]byte, []int) {
	return file_mintwatcher_event_proto_rawDescGZIP(), []int{0}
}

func (x *Refill) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Refill) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Refill) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Refill) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Refill) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Refill) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

// RefillAck is a reply for Refill
type RefillAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Success is true in case of success
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`      // Error contains error descrition in case of failure
}

func (x *RefillAck) Reset() {
	*x = RefillAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mintwatcher_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefillAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefillAck) ProtoMessage() {}

func (x *RefillAck) ProtoReflect() protoreflect.Message {
	mi := &file_mintwatcher_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefillAck.ProtoReflect.Descriptor instead.
func (*RefillAck) Descriptor() ([]byte, []int) {
	return file_mintwatcher_event_proto_rawDescGZIP(), []int{1}
}

func (x *RefillAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefillAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mintwatcher_event_proto protoreflect.FileDescriptor

var file_mintwatcher_event_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x69, 0x6e, 0x74, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0xa4, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x66, 0x69, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a, 0x09, 0x52, 0x65, 0x66, 0x69, 0x6c,
	0x6c, 0x41, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x42, 0x26, 0x5a, 0x09, 0x2e, 0x3b, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x72, 0xaa, 0x02, 0x18, 0x4d, 0x69, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mintwatcher_event_proto_rawDescOnce sync.Once
	file_mintwatcher_event_proto_rawDescData = file_mintwatcher_event_proto_rawDesc
)

func file_mintwatcher_event_proto_rawDescGZIP() []byte {
	file_mintwatcher_event_proto_rawDescOnce.Do(func() {
		file_mintwatcher_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_mintwatcher_event_proto_rawDescData)
	})
	return file_mintwatcher_event_proto_rawDescData
}

var file_mintwatcher_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mintwatcher_event_proto_goTypes = []interface{}{
	(*Refill)(nil),    // 0: event.Refill
	(*RefillAck)(nil), // 1: event.RefillAck
}
var file_mintwatcher_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mintwatcher_event_proto_init() }
func file_mintwatcher_event_proto_init() {
	if File_mintwatcher_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mintwatcher_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Refill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mintwatcher_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefillAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mintwatcher_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mintwatcher_event_proto_goTypes,
		DependencyIndexes: file_mintwatcher_event_proto_depIdxs,
		MessageInfos:      file_mintwatcher_event_proto_msgTypes,
	}.Build()
	File_mintwatcher_event_proto = out.File
	file_mintwatcher_event_proto_rawDesc = nil
	file_mintwatcher_event_proto_goTypes = nil
	file_mintwatcher_event_proto_depIdxs = nil
}
