// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.10.1
// source: mintwatcher_request.proto

package watcher

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// AddRemove is a request to the service to add or remove a wallet by it's public key
type AddRemove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service   string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`     // Service name (to differentiate multiple requestors): 1..64
	PublicKey []string `protobuf:"bytes,2,rep,name=publicKey,proto3" json:"publicKey,omitempty"` // Wallet address in Base58
	Add       bool     `protobuf:"varint,3,opt,name=add,proto3" json:"add,omitempty"`            // True to add wallet, otherwise to remove it
}

func (x *AddRemove) Reset() {
	*x = AddRemove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mintwatcher_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRemove) ProtoMessage() {}

func (x *AddRemove) ProtoReflect() protoreflect.Message {
	mi := &file_mintwatcher_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRemove.ProtoReflect.Descriptor instead.
func (*AddRemove) Descriptor() ([]byte, []int) {
	return file_mintwatcher_request_proto_rawDescGZIP(), []int{0}
}

func (x *AddRemove) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *AddRemove) GetPublicKey() []string {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *AddRemove) GetAdd() bool {
	if x != nil {
		return x.Add
	}
	return false
}

// AddRemoveReply is a reply for AddRemove
type AddRemoveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Success is true in case of success
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`      // Error contains error descrition in case of failure
}

func (x *AddRemoveReply) Reset() {
	*x = AddRemoveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mintwatcher_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRemoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRemoveReply) ProtoMessage() {}

func (x *AddRemoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_mintwatcher_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRemoveReply.ProtoReflect.Descriptor instead.
func (*AddRemoveReply) Descriptor() ([]byte, []int) {
	return file_mintwatcher_request_proto_rawDescGZIP(), []int{1}
}

func (x *AddRemoveReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddRemoveReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mintwatcher_request_proto protoreflect.FileDescriptor

var file_mintwatcher_request_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x69, 0x6e, 0x74, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x64, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x61, 0x64, 0x64, 0x22, 0x40, 0x0a, 0x0e, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x28, 0x5a,
	0x09, 0x2e, 0x3b, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0xaa, 0x02, 0x1a, 0x4d, 0x69, 0x6e,
	0x74, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mintwatcher_request_proto_rawDescOnce sync.Once
	file_mintwatcher_request_proto_rawDescData = file_mintwatcher_request_proto_rawDesc
)

func file_mintwatcher_request_proto_rawDescGZIP() []byte {
	file_mintwatcher_request_proto_rawDescOnce.Do(func() {
		file_mintwatcher_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_mintwatcher_request_proto_rawDescData)
	})
	return file_mintwatcher_request_proto_rawDescData
}

var file_mintwatcher_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mintwatcher_request_proto_goTypes = []interface{}{
	(*AddRemove)(nil),      // 0: request.AddRemove
	(*AddRemoveReply)(nil), // 1: request.AddRemoveReply
}
var file_mintwatcher_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mintwatcher_request_proto_init() }
func file_mintwatcher_request_proto_init() {
	if File_mintwatcher_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mintwatcher_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRemove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mintwatcher_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRemoveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mintwatcher_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mintwatcher_request_proto_goTypes,
		DependencyIndexes: file_mintwatcher_request_proto_depIdxs,
		MessageInfos:      file_mintwatcher_request_proto_msgTypes,
	}.Build()
	File_mintwatcher_request_proto = out.File
	file_mintwatcher_request_proto_rawDesc = nil
	file_mintwatcher_request_proto_goTypes = nil
	file_mintwatcher_request_proto_depIdxs = nil
}
