// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package watcher

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AddRemove is a request to the service to add or remove a wallet by it's public key
type AddRemove struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	PublicKey            []string `protobuf:"bytes,2,rep,name=publicKey,proto3" json:"publicKey,omitempty"`
	Add                  bool     `protobuf:"varint,3,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemove) Reset()         { *m = AddRemove{} }
func (m *AddRemove) String() string { return proto.CompactTextString(m) }
func (*AddRemove) ProtoMessage()    {}
func (*AddRemove) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_4d73036cfa1f9269, []int{0}
}
func (m *AddRemove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemove.Unmarshal(m, b)
}
func (m *AddRemove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemove.Marshal(b, m, deterministic)
}
func (dst *AddRemove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemove.Merge(dst, src)
}
func (m *AddRemove) XXX_Size() int {
	return xxx_messageInfo_AddRemove.Size(m)
}
func (m *AddRemove) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemove.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemove proto.InternalMessageInfo

func (m *AddRemove) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *AddRemove) GetPublicKey() []string {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *AddRemove) GetAdd() bool {
	if m != nil {
		return m.Add
	}
	return false
}

// AddRemoveReply is a reply for AddRemove
type AddRemoveReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoveReply) Reset()         { *m = AddRemoveReply{} }
func (m *AddRemoveReply) String() string { return proto.CompactTextString(m) }
func (*AddRemoveReply) ProtoMessage()    {}
func (*AddRemoveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_4d73036cfa1f9269, []int{1}
}
func (m *AddRemoveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoveReply.Unmarshal(m, b)
}
func (m *AddRemoveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoveReply.Marshal(b, m, deterministic)
}
func (dst *AddRemoveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoveReply.Merge(dst, src)
}
func (m *AddRemoveReply) XXX_Size() int {
	return xxx_messageInfo_AddRemoveReply.Size(m)
}
func (m *AddRemoveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoveReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoveReply proto.InternalMessageInfo

func (m *AddRemoveReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddRemoveReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*AddRemove)(nil), "request.AddRemove")
	proto.RegisterType((*AddRemoveReply)(nil), "request.AddRemoveReply")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_request_4d73036cfa1f9269) }

var fileDescriptor_request_4d73036cfa1f9269 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x42, 0xb9,
	0x38, 0x1d, 0x53, 0x52, 0x82, 0x52, 0x73, 0xf3, 0xcb, 0x52, 0x85, 0x24, 0xb8, 0xd8, 0x8b, 0x53,
	0x8b, 0xca, 0x32, 0x93, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x21, 0x19,
	0x2e, 0xce, 0x82, 0xd2, 0xa4, 0x9c, 0xcc, 0x64, 0xef, 0xd4, 0x4a, 0x09, 0x26, 0x05, 0x66, 0x0d,
	0xce, 0x20, 0x84, 0x80, 0x90, 0x00, 0x17, 0x73, 0x62, 0x4a, 0x8a, 0x04, 0xb3, 0x02, 0xa3, 0x06,
	0x47, 0x10, 0x88, 0xa9, 0xe4, 0xc0, 0xc5, 0x07, 0x37, 0x36, 0x28, 0xb5, 0x20, 0xa7, 0x12, 0x6c,
	0x76, 0x69, 0x72, 0x72, 0x6a, 0x71, 0x31, 0xd8, 0x6c, 0x8e, 0x20, 0x18, 0x57, 0x48, 0x84, 0x8b,
	0x35, 0xb5, 0xa8, 0x28, 0xbf, 0x48, 0x82, 0x09, 0x6c, 0x27, 0x84, 0xe3, 0xa4, 0x16, 0xc5, 0x5e,
	0x9e, 0x58, 0x92, 0x9c, 0x91, 0x5a, 0xb4, 0x8a, 0x49, 0xca, 0x37, 0x33, 0xaf, 0x24, 0x38, 0x35,
	0x2f, 0x25, 0xb5, 0x48, 0x2f, 0x1c, 0x22, 0xa8, 0x17, 0x04, 0xf1, 0x40, 0x12, 0x1b, 0xd8, 0x43,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xaa, 0xf1, 0x95, 0xe1, 0x00, 0x00, 0x00,
}
